#!/bin/bash -ex
#
# Juju >= 2.0 Only (Native deploy - No `juju-deployer`)
#

# Set overrides, if not already set.
[[ -z "$GATEWAY" ]] && export GATEWAY="10.13.3.1"
[[ -z "$CIDR_EXT" ]] && export CIDR_EXT="10.13.3.0/24"
[[ -z "$FIP_RANGE" ]] && export FIP_RANGE="10.13.3.128:10.13.3.191"
[[ -z "$NAMESERVER" ]] && export NAMESERVER="10.13.3.1"
[[ -z "$CIDR_PRIV" ]] && export CIDR_PRIV="172.16.0.0/12"
[[ -z "$SWIFT_IP" ]] && export SWIFT_IP="10.245.161.162"  # Cirros image hosted on serverstack

# Accept network type as first parameter, assume gre if unspecified
net_type=${1:-"gre"}

# Configure neutron networking on the deployed cloud
source novarc_auto
./bin/neutron-ext-net-ksv3 --network-type vlan --vlan_id 2893 -g $GATEWAY -c $CIDR_EXT -f $FIP_RANGE ext_net 
./bin/neutron-tenant-net-ksv3 --network-type $net_type -t admin -r provider-router -N $NAMESERVER private $CIDR_PRIV



# Create demo/testing users, tenants and flavors
openstack project show demo || openstack project create demo
openstack user show demo || openstack user create --project demo --password pass --enable --email demo@dev.null demo
openstack role show Member || openstack role create Member
openstack role add --user demo --project demo Member
openstack project show alt_demo || openstack project create alt_demo
openstack user show alt_demo || openstack user create --project alt_demo --password secret --enable --email alt_demo@dev.null alt_demo
openstack role add --user alt_demo --project alt_demo Member

openstack flavor show m1.cirros || openstack flavor create --id 6 --ram 64 --disk 1 --vcpus 1 m1.cirros
openstack flavor show m1.tempest || openstack flavor create --id 7 --ram 256 --disk 5 --vcpus 1 m1.tempest
openstack flavor show m2.tempest || openstack flavor create --id 8 --ram 512 --disk 5 --vcpus 1 m2.tempest


# Load images into glance
tools/images_s390x-v3.sh

# Set security groups and rules
tools/sec_groups-v3.sh
