#!/bin/bash -e

function usage() {
  echo -e "
Renders one or more Juju 1+2 bundles from an old-style multiple-inheritance
bundle.  The source bundle must use "charm: cs:foo" (not branch: foo).

New/updated bundles will be written/overwritten to a "rendered" subdir.

  Syntax:
    ./render2.sh -t <optional space-separated list of targets> <bundle file(s)>

  Usage examples:
    Render specific inheritance targets from a bundle:
    ./render2.sh -t \"trusty-liberty trusty-mitaka\" foo/source_bundle.yaml

    Render specific inheritance targets from all bundles in a dir:
    ./render2.sh -t \"trusty-liberty trusty-mitaka\" foo/*.yaml

    Render the default inheritance targets from a bundle:
    ./render2.sh foo/source_bundle.yaml

    Render the default inheritance targets from a wildcard:
    ./render2.sh foo/*.yaml

    In all of these examples, the rendered files will reside in the
    foo/rendered/ dir.
"
}

while getopts ":t:" opt
   do
     case $opt in
        t ) TARGETS=$OPTARG;;
        * ) usage; exit 1;;
     esac
done

shift $(($OPTIND - 1))
SRC_BUNDLE_FILES=$@
[[ -z "$SRC_BUNDLE_FILES" ]] && (usage; exit 1)

TARGETS_DEFAULT="trusty-liberty trusty-mitaka xenial-mitaka"
TARGETS="${TARGETS-$TARGETS_DEFAULT}"
WARNING_TXT="# Do not edit this file by hand.  Changes may be lost as it was rendered from another bundle."

echo "Bundle files: $SRC_BUNDLE_FILES"
echo "Targets: $TARGETS"

if [[ ! -d $HOME/tools/bot-control ]]; then
  mkdir -vp $HOME/tools
  git clone https://github.com/openstack-charmers/bot-control $HOME/tools/bot-control
fi

for SRC_BUNDLE in $SRC_BUNDLE_FILES;do
  RENDER_DIR="$(dirname "$SRC_BUNDLE")/rendered"
  [[ ! -d "$RENDER_DIR" ]] && mkdir -vp $RENDER_DIR

  for COMBO in $TARGETS; do
    # Reduce bundle to one specific inheritance target
    OUT_FILE="$RENDER_DIR/$(basename $SRC_BUNDLE .yaml)-$COMBO.yaml"
    $HOME/tools/bot-control/tools/bundle-reducer -y -i $SRC_BUNDLE -o $OUT_FILE -t $COMBO

    # Add warning comment to the top of all rendered files
    sed -i "1i${WARNING_TXT}" $OUT_FILE
  done
done
